// Generated by CoffeeScript 1.4.0
(function() {
  var homeDto;

  homeDto = {
    baseLink: "http://apps.readyservice.com/RS/",
    links: [
      {
        label: "Locations",
        link: "SBM/RSViewLocations.aspx",
        img: "locations.png"
      }, {
        label: "Service Calls",
        link: "SBM/RSViewCalls.aspx",
        img: "service_calls.png"
      }, {
        label: "Contacts",
        link: "SBM/RSViewContacts.aspx",
        img: "contacts.png"
      }, {
        label: "Inventory",
        link: "SBM/RSViewInventoryPart.aspx",
        img: "inventory.png"
      }, {
        label: "Estimates",
        link: "SBM/RSViewEstimates.aspx",
        img: "estimates.png"
      }, {
        label: "Work Orders",
        link: "SBM/RSViewWorkOrders.aspx",
        img: "work_orders.png"
      }, {
        label: "Issues",
        link: "SBM/RSViewIssues.aspx",
        img: "issues.png"
      }, {
        label: "Equipment",
        link: "SBM/RSViewInventoryEquip.aspx",
        img: "Equipment.png"
      }, {
        label: "Service Visits",
        link: "SBM/RSViewVisits.aspx",
        img: "service_visits.png"
      }, {
        label: "Schedule",
        link: "Modules/ReadySchedule/People.aspx",
        img: "schedule.png"
      }, {
        label: "Communication",
        link: "Bliss/WallPost.aspx",
        img: "comm_board.png"
      }, {
        label: "Documents",
        link: "SBM/RSSBMHome.aspx",
        img: "documents.png"
      }
    ]
  };

  window.homeDto = homeDto;

}).call(this);
